language: java
addons:
  sonarcloud:
    organization: "seblucas"
script:
  # other script steps might be done before running the actual analysis
  - mkdir output
  - javac src/HelloWorld.java -d output
  - sonar-scanner
